---
- name: Update n1 servers
  hosts: n1

  tasks:
  - name: Create Directory
    files:
      path: ~/opt/devops_dir
      state: directory

  - name: Create Directory
    files:
      path: ~/opt/devops_dir_1
      state: directory   

- name: Update n2 servers
  hosts: n2

  tasks:
  - name: Create Directory
    files:
      path: ~/opt/devops_dir_1
      state: directory

  - name: Create Directory
    files:
      path: ~/opt/devops_dir_2
      state: directory

- name: Update g1 servers
  hosts: g1

  tasks:
  - name: Create Directory
    files:
      path: ~/opt/devops_dir_group1
      state: directory

  - name: Create Directory
    files:
      path: ~/opt/devops_dir_group1
      state: directory         
...
