---
- name: Variables Demo
  hosts: g3
  become: yes
  vars:
    myusername: JohnsonBV

  tasks:
  - name: update dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html           
...
